### ISSUE TITLE
Method not found: 'System.Threading.Tasks.Task`1<RevoltSharp.UserMessage> RevoltSharp.MessageHelper.SendMessageAsync(RevoltSharp.Channel, System.String, RevoltSharp.Embed[], System.String[], RevoltSharp.MessageMasquerade, RevoltSharp.MessageInteractions, RevoltSharp.MessageReply[])'.

### ISSUE THREAD

**Issue by ricoshett** [FluxpointDev/StoatSharp#28]
For some reason whenever I use `await ReplyAsync()` the following error occurs.

**Comment by xXBuilderBXx** [comment]
Are you using the latest lib version 7.4.0?

**Comment by xXBuilderBXx** [comment]
Found the issue it's because RevoltSharp.Commands has not been updated to used the main RevoltSharp lib correctly, a fix for this will be coming in an hour or two.

**Comment by xXBuilderBXx** [comment]
Fixed in latest v7.5.0 RevoltSharp and Command v1.2.0
